---
- name: CREATE LOOPBACK INTERFACE
  hosts: csr
  gather_facts: False
  connection: local
  become: yes
  become_method: enable

  tasks:
    - name: Creating loopback 
      ios_interface:
        name: Loopback100
        enabled: True
        description: Loopback interface 100 created with Ansible
    - name: Assigning IP to loopback
      ios_l3_interface:
        name: Loopback100
        ipv4: 10.10.10.100/32
